# site properties and page defaults
title: Grieshop Lab
subtitle: Evolutionary Genetics & Genomics
description: We study the evolutionary causes and consequences of genetic variation underlying fitness trade-offs between sexes, traits, tissues, life-stages, and environments.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: K.Grieshop@uea.ac.uk
  orcid: 0000-0002-XXXX-XXXX
  google-scholar: 52Zoz-wAAAAJ
  github: karlgrieshop
  twitter: karlgrieshop
  youtube: karlgrieshop

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts
  - images
  - assets

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
